server :
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/todo
    username: root
    password:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      format_sql : true
      ddl-auto: update